### ISSUE TITLE
TronWeb should return the txID for broadcasted transactions

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#101]
[At the moment, TronWeb only returns the broadcast result.](https://github.com/tronprotocol/tron-web/blob/8b8ece88679f90dad86ed8c7c5cde55f61ddacd4/src/lib/trx.js#L659) It would be more useful if it also returned the transactionID.

This is how it's done (internally) in TronLink - it returns the signedTransaction itself under `__payload__`: 
![image](https://user-images.githubusercontent.com/16869626/48918638-d9fb8280-ee85-11e8-8ea5-bf24be9d3bf3.png)

**Comment by sullof** [comment]
I will add it asap.
