### ISSUE TITLE
[Enhancement] - Add a note to the transaction

### ISSUE THREAD

**Issue by serderovsh** [tronprotocol/tron-web#104]
I do not understand, for a python I wrote a similar condition works well. And in TronWEB gives an error.
```
{ code: 'SIGERROR',
  message: '76616c6964617465207369676e6174757265206572726f72' }
```

This is not a complete example.
```javascript
sendWithNote(to = false,
                 amount = 0,
                 note = false,
                 tokenID = false,
                 from = this.tronWeb.defaultAddress.hex,
                 callback = false)
    {
        if(tokenID === false) {
            let transaction = this.sendTrx(to, amount, from, callback);
            transaction.then(transaction => {
                //or transaction.raw_data.data = this.tronWeb.fromUtf8(note);
                transaction['raw_data']['data'] = this.tronWeb.fromUtf8(note);
            });
            return transaction;
        }

        return this.sendToken(to, amount, tokenID, from, callback);
    }
```

Note: **JSON results are identical**

**Comment by serderovsh** [comment]
> The method is asynchronous. You're executing the sendTrx call and returning a promise, you're not returning the transaction.

let sendTransaction;
    sendTransaction = await tronWeb.transactionBuilder.sendTrx('to', 0);
    sendTransaction.raw_data.data = 'hex message';

    const signedTransaction = await tronWeb.trx.sign(sendTransaction);
    console.group('Signed');
    console.log('- Transaction:\n' + JSON.stringify(signedTransaction, null, 2), '\n');
    console.groupEnd(); // no error {raw_data.data = 'hex_message'} Added

    const sendRaw = await tronWeb.trx.sendRawTransaction(signedTransaction); // error
    console.group('Success');
    console.log('- Transaction:\n' + JSON.stringify(sendRaw, null, 2), '\n');
    console.groupEnd();

**Comment by serderovsh** [comment]
<details><summary>Result JSON (show)</summary>


Signed update token transaction
  - Transaction:
  {
    "txID": "44b6072e32c45eae467a8111931cf89fc88cf0469c41044a737f9db1cb9c7662",
    "raw_data": {
      "contract": [
        {
          "parameter": {
            "value": {
              "amount": 1000,
              "owner_address": "41aa65cffbc911a08130bc7f0d308a8607f650b40e",
              "to_address": "41a83fc88be4b88a1a341d89f88127ab736bfad359"
            },
            "type_url": "type.googleapis.com/protocol.TransferContract"
          },
          "type": "TransferContract"
        }
      ],
      "ref_block_bytes": "9197",
      "ref_block_hash": "b13cb3b026bfe723",
      "expiration": 1543246794000,
      "timestamp": 1543246737881,
      "data": "0x68656c6c6f"
    },
    "signature": [
      "6373fe71be48607ad034e798dce0cfebf6272b30d4764f660331fa887a9eedaac4b53a6295711be1cb75b044c923a458fe0116ce1e0994ecf674d16cbf2c9f6e00"
    ]
  }

-----
{ code: 'SIGERROR',
  message: '76616c6964617465207369676e6174757265206572726f72' }
Success
  - Transaction:
  {
    "code": "SIGERROR",
    "message": "76616c6964617465207369676e6174757265206572726f72"
  }



</details>

**Comment by serderovsh** [comment]
I mock the code :)

**Does not work**
```javascript
    let sendTransaction;
    sendTransaction = await tronWeb.transactionBuilder.sendTrx('to', 1000).then((result) =>
    {
        let tx =result;
        tx['raw_data']['data'] = TronWeb.toHex('hello');
        tronWeb.trx.sign(tx).then(result2 => {
            console.log('- Transaction:\n' + JSON.stringify(result2 , null, 2), '\n'); //no error

            tronWeb.trx.sendRawTransaction(result2).then(result3 => {
                console.log('- Transaction:\n' + JSON.stringify(result3, null, 2), '\n'); // error
            });
        });
    });

```

**Comment by Kondax** [comment]
Are you sure `raw_data.data` is the correct parameter?

**Comment by serderovsh** [comment]
> Are you sure `raw_data.data` is the correct parameter?

TronScan:
https://github.com/tronscan/tronscan-node-client/blob/master/src/client/http.js#L50

My Library for Python
https://raw.githubusercontent.com/iexbase/tron-api-python/master/tronapi/trx.py#L342

**Comment by serderovsh** [comment]
Log Success transaction:

```
2018-11-26 20:02:16,790 - DEBUG - urllib3.connectionpool - https://api.trongrid.io:443 "POST /wallet/gettransactionbyid HTTP/1.1" 200 663
{
    "ret": [
        {
            "contractRet": "SUCCESS"
        }
    ],
    "signature": [
        "9aa6fcf4177574de5474b5c29716efe92b4f794ea0966c531ac7dad1d1cd14852d996d752e6e758642fcad630c46222e7b46a5ac5f05dc9e0a79a1a10e871eb700"
    ],
    "txID": "c3118fdc4147b2c60d83a67e2723e49504cf0ad522040407eeb0d256942cd258",
    "raw_data": {
        "data": "4b6f6e646178",
        "contract": [
            {
                "parameter": {
                    "value": {
                        "amount": 1000,
                        "owner_address": "41aa65cffbc911a08130bc7f0d308a8607f650b40e",
                        "to_address": "41a83fc88be4b88a1a341d89f88127ab736bfad359"
                    },
                    "type_url": "type.googleapis.com/protocol.TransferContract"
                },
                "type": "TransferContract"
            }
        ],
        "ref_block_bytes": "97f7",
        "ref_block_hash": "3f73e576a3470380",
        "expiration": 1543251693000,
        "timestamp": 1543251636051
    }
}
```

**Comment by Kondax** [comment]
Shouldn't the `data` option be added before the transaction is created? The txID will change if you change the transaction (by adding data), which is why you're seeing the signature error I believe

**Comment by serderovsh** [comment]
Note is checked in "sign"
![2018-11-26_20-47-22](https://user-images.githubusercontent.com/24723913/49032066-b81f3a00-f1bc-11e8-86bf-0625662f4941.png)

**Comment by serderovsh** [comment]
tronscan-node-client
![2018-11-26_21-11-36](https://user-images.githubusercontent.com/24723913/49033555-90ca6c00-f1c0-11e8-8e89-47fc7b8e3237.png)

**Comment by Kondax** [comment]
Tronscan uses a custom API. By changing the transaction after creating it the txID changes. @sullof Any idea if the http api supports a data prop?

**Comment by serderovsh** [comment]
> Tronscan uses a custom API. By changing the transaction after creating it the txID changes. @sullof Any idea if the http api supports a data prop?

"/createtransaction" - The parameters created here can be changed, but if they are sent ("/gettransactionsign"), then everything cannot be changed.

**Comment by serderovsh** [comment]
I use this scheme in "PHP", "Python" and "Go". 
**Everything works, "raw_data.data" is recording data**

**Comment by sullof** [comment]
I am investigating it.

**Comment by Kondax** [comment]
So the transactionID doesn't take into account the data field?

**Comment by serderovsh** [comment]
raw_data.data - there you can store a huge amount of text, arrays of 100,000 lines. This parameter is not taken into account when creating an ID.

**Comment by sullof** [comment]
@serderovsh @Kondax 
I fixed it. Look at https://github.com/tronprotocol/tron-web/pull/106

**Comment by sullof** [comment]
@kondax In TronScan the signing of a transaction is done with the following function:
```
function signTransaction(priKeyBytes, transaction) {

  if (typeof priKeyBytes === 'string') {
    priKeyBytes = hexStr2byteArray(priKeyBytes);
  }

  let raw = transaction.getRawData();
  let rawBytes = raw.serializeBinary();
  let hashBytes = SHA256(rawBytes);
  let signBytes = ECKeySign(hashBytes, priKeyBytes);
  let uint8Array = new Uint8Array(signBytes);
  let count = raw.getContractList().length;
  for (let i = 0; i < count; i++) {
    transaction.addSignature(uint8Array);
  }

  return {
    transaction,
    hex: byteArray2hexStr(transaction.serializeBinary()),
  };
}
```
where all the data in the raw_data property are signed with the passed priKey, as I would expect that it does.  
Instead, TronWeb just signs the txID:
```
export function signTransaction(priKeyBytes, transaction) {
    if (typeof priKeyBytes === 'string')
        priKeyBytes = hexStr2byteArray(priKeyBytes);

    const txID = transaction.txID;
    const signature = ECKeySign(hexStr2byteArray(txID), priKeyBytes);

    transaction.signature = [ signature ];
    return transaction;
}
```
I would expect that the two are incompatible, but actually it seems that both work.
Any idea?

**Comment by serderovsh** [comment]
@sullof This is due precisely to "offlineSign".
I have now written a standalone TX signature method, and I also received a similar error that I described at the beginning.


```python
privkey = PrivateKey('...')
signingkey = ecdsa.SigningKey.from_string(privkey.__bytes__(), curve=ecdsa.SECP256k1)
SIG = signingkey.sign(bytes(tx_data['txID'], encoding='utf-8'), sigencode=ecdsa.util.sigencode_der_canonize)

tx_data['signature'] = [SIG.hex()]
result = tron.trx.broadcast(tx_data)

//{'code': 'SIGERROR', 'message': '76616c6964617465207369676e6174757265206572726f72'}


```

**Comment by serderovsh** [comment]
The problem is connected with offline signature.
I was able to reproduce the error in "Python" by creating offline signatures.

https://github.com/iexbase/tron-api-python/blob/master/tronapi/trx.py#L427

**Comment by Kondax** [comment]
@sullof Its the way in which the txID is generated. Tronscan still only signs the txID, it's generating it locally (hashBytes) instead of using the http node.

So, I was originally correct in thinking that it's due to the data prop not being accounted for in the txID. We can't support this until the HTTP API allows us to provide a data prop.

**Comment by serderovsh** [comment]
Online signature can be made as an alternative.

```javascript
    async onlineSign(transaction = false, privateKey = this.tronWeb.defaultPrivateKey, callback = false) 
	{
        if(utils.isFunction(privateKey)) {
            callback = privateKey;
            privateKey = this.tronWeb.defaultPrivateKey;
        }

        if(!callback)
            return this.injectPromise(this.onlineSign, transaction, privateKey);

        if(!utils.isObject(transaction))
            return callback('Invalid transaction provided');

        if(transaction.signature)
            return callback('Transaction is already signed');

        try {
            const address = this.tronWeb.address.toHex(
                this.tronWeb.address.fromPrivateKey(privateKey)
            ).toLowerCase();

            if(address !== transaction.raw_data.contract[0].parameter.value.owner_address.toLowerCase())
                return callback('Private key does not match address in transaction');

            this.tronWeb.fullNode.request(
                'wallet/gettransactionsign', {
                    transaction,
                    privateKey
                },
                'post'
            ).then(result => {
                callback(null, result);
            }).catch(err => callback(err));
			
        } catch(ex) {
            callback(ex);
        }
    }
```

**Comment by Kondax** [comment]
Signing is not the problem. Generating the txID is.

**Comment by serderovsh** [comment]
https://github.com/protocolbuffers/protobuf

**Comment by Kondax** [comment]
It's necessary for getting the transaction data

**Comment by serderovsh** [comment]
@Kondax Is it worth serializing the data from the proto for one parameter and working with it? (I see only this option)?

**Comment by serderovsh** [comment]
Can still give several options for signing data?
1). sign()
2). onlineSign().

**Comment by serderovsh** [comment]
If you plan to expand the capabilities of "TronWeb", in this case it is worth working with "Proto", if for one parameter "raw_data.data", then I do not see the point!

**Comment by Kondax** [comment]
We do not want online signing, or easy transfer. TronWeb will not support
such methods as they're highly insecure.

**Comment by serderovsh** [comment]
@sullof, This question can be solved? 
If not, I will make a temporary online signature!

**Comment by Kondax** [comment]
We will look into it today. We won't be adding online signing to TronWeb.

**Comment by serderovsh** [comment]
> . We won't be adding online signing to TronWeb.

I was not going to offer to implement an online subscription in the plugin "TronWeb".

I am writing one project in “typescript”, and I need the parameter “raw_data.data”!
If you are unable to implement it now, in this case I will add an online signature method to my project.

Online signature will be made only if the user wants to add a note to the transaction.
This parameter is mainly used to check the order number.

**Comment by Kondax** [comment]
Yes, in which case I suggest adding it to your own project until TronWeb
finds a viable solution for generating Transaction IDs locally.
