### ISSUE TITLE
Support PHP

### ISSUE THREAD

**Issue by serderovsh** [tronprotocol/tron-web#11]
We developed the library "TronAPI" for "PHP"

https://github.com/iexbase/tron-api

**Comment by gitwujiaolong** [comment]
well done!!!

**Comment by serderovsh** [comment]
The project is partially changed to the structure of "[Kondax](https://github.com/tronprotocol/tron-web/issues/8)"

**Comment by kookiekrak** [comment]
i added a link in our docs https://developers.tron.network/

**Comment by crezmer-test** [comment]
while installing composer require iexbase/tron-api

i am getting following error

 Problem 1
    - The requested package iexbase/tron-api No version set (parsed as 1.0.0) is satisfiable by iexbase/tron-api[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - simplito/elliptic-php 1.0.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - simplito/elliptic-php 1.0.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - simplito/elliptic-php 1.0.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - simplito/elliptic-php 1.0.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - simplito/elliptic-php 1.0.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - Installation request for simplito/elliptic-php ^1.0 -> satisfiable by simplito/elliptic-php[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
