### ISSUE TITLE
Prefix rule is different from Ethereum

### ISSUE THREAD

**Issue by emn178** [tronprotocol/tron-web#111]
https://github.com/tronprotocol/tron-web/blob/efd6eb7b73ff6942a75ef40049963aa815b9e5bb/src/lib/trx.js#L5-L6

In Ethereum, the prefix rule is 
```
"\x19Ethereum Signed Message:\n" + len(message)
```
see https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

You change it to fixed "32". Is this a bug or feature?

**Comment by serderovsh** [comment]
@emn178, Thanks

**Comment by Kondax** [comment]
Whilst I can change this to calculate the length of the string at compile time, this should always actually return the same length as it's signing the hash of a message, not a message specifically.

**Comment by sullof** [comment]
> Whilst I can change this to calculate the length of the string at compile time, this should always actually return the same length as it's signing the hash of a message, not a message specifically.

That makes sense because TronWeb uses it to sign transaction IDs.
But I guess that if someone uses it to sign messages, it will have an impact.

**Comment by Kondax** [comment]
Even for messages, it calculates the hash. This prevents people from signing transaction IDs.

**Comment by sullof** [comment]
Good. So, we can keep it the way it is. If so, we can close this issue.

**Comment by emn178** [comment]
Some dapp will sign message with plain text for verification of account. looks like this.
![image](https://user-images.githubusercontent.com/3477613/49336181-2a1dd600-f638-11e8-918b-3f8514c3531e.png)

Keep fixed "32" also works. It's no need to follow Ethereum everything. I just want to make sure if it's correct logic. Does anybody know why it uses length of message in Ethereum?

**Comment by Kondax** [comment]
Yes, but it will calculate the hash of that message and sign that. Hence 32
working all the time.

Ethereum says the length so you can calculate the correct header. You don't
have to sign a hash, this is just how libraries and ercrecover work.
