### ISSUE TITLE
tronWeb.contract({abi:abi}) error

### ISSUE THREAD

**Issue by shapowang** [tronprotocol/tron-web#112]
https://developers.tron.network/v3.0/reference#tronweb-contract-method-documentation
give such example code:
`let abi = [{"constant":false,"inputs":[{"name":"number","type":"uint256"}],"name":"constructor","outputs":[{"name":"result","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"number","type":"uint256"}],"name":"calculateValue","outputs":[{"name":"result","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"input","type":"uint256"},{"indexed":false,"name":"result","type":"uint256"}],"name":"Notify","type":"event"}];

let contract = await tronWeb.contract({abi:abi});

let result = await contract.calculateValue(5).call();`

I tried it in my page with a valid tronWeb instance,error as below:
`Uncaught (in promise) TypeError: e.forEach is not a function TypeError: e.forEach is not a function
    at e.value (TronWeb.node.js:formatted:1)
    at new e (TronWeb.node.js:formatted:1)
    at t.value (TronWeb.node.js:formatted:1)
    at <anonymous>:3:32
    at <anonymous>:5:59`

any suggestions?

**Comment by Kondax** [comment]
Please change {abi:abi} to just abi

**Comment by shapowang** [comment]
done,thanks,then you need update the wrong document example

**Comment by tmao1129** [comment]
Thanks, documentation has been updated.
