### ISSUE TITLE
[BUG] contract.abi is undefined when the contract is created by another contract instead of being deployed

### ISSUE THREAD

**Issue by fyang1024** [tronprotocol/tron-web#120]
I have Factory contract. There is a function in it creating another contract. The function returns the contract address. So far so good. But when I 
```await tronWeb.contract().at(contractAddress)```
 to get the new contract,
```
TypeError: Cannot read property 'entrys' of undefined
      at e.<anonymous> (node_modules/tronweb/dist/webpack:/src/lib/contract/index.js:198:39)
```
 is thrown.
I looked at the tronweb code, it shows that `this.loadAbi(contract.abi.entrys);` threw the error. Obviously `contract.abi` is `undefined` in this case. Not sure if this is java-tron problem or tronweb problem.

**Comment by Kondax** [comment]
This is not an issue with TronWeb but with java-tron instead. I'd recommend opening an issue there.

**Comment by Cashik** [comment]
Still actual. There is a solution?
