### ISSUE TITLE
[question] Concern with privateKey usage in docs

### ISSUE THREAD

**Issue by vicpon** [tronprotocol/tron-web#123]
I'm new to this, so please forgive my ignorance. I've been looking at the meta-coin example and the sample code here in the readme and both have a hard-coded privateKey that is used to instantiate tronWeb. I assume that the only reason they're hard-coded is to demonstrate how to use tronWeb and not to indicate that it's typical/normal to store the privateKey in plain-text and unencrypted right? You would typically ask the user to enter their private key, right? I feel like the documentation should be clearer about this, at least in a comment where the privateKey is declared/used.

**Comment by sullof** [comment]
This is the right way to set your `tronbox.js` file:
https://github.com/Tronbox-boxes/bare-box/blob/master/tronbox.js

**Comment by vicpon** [comment]
How would you use tronweb client side without exposing your private key? Would TronLink be required in that case?

**Comment by sullof** [comment]
TronWeb is used locally. If in the browser, the private key can be set directly or using a wallet. In both cases, that private key will never leave the local environment (i.e. the browser). If you don't use TronWeb for that you have two alternatives: handling the signature by yourself (which is technically hard) or send the private key to the HTTP API, which is bad and should never be done. By the way, JavaTron provides APIs to sign for completeness, but we never suggest to use them, except if they are working on their own, private network.

**Comment by vicpon** [comment]
How is it secure in the browser though? If a malicious user wants the key they could just open the dev console and find it. Minifying and obfuscating the code would make it harder to find but not impossible.

**Comment by sullof** [comment]
First off, the right way to go is to use a wallet like TronLink (who uses TronWeb) to handle the signatures. But, in case you don't use a wallet, when you connect to a dApp and input your private key, you are the only one that can hack yourself.

**Comment by sullof** [comment]
Anyway, for questions like this, can you please post in the #tronweb channel in our Discord community?

**Comment by vicpon** [comment]
Will do, my apologies.
