### ISSUE TITLE
Anti-fraud and theft system for TRON chain

### ISSUE THREAD

**Issue by cryptozwerg** [tronprotocol/tron-web#129]
I saw a lot of frauds/thefts in the TRON network during the last two months. Therefore I want to suggest a  community driven development and realization of  police/investigation/court system for frauds. In my opinion such system will help A LOT with ADOPTION, because ppl will see Tronix as the only coin that has a security layer against frauds/thefts. If interested pls comment so I can do a little presentation of my idea. Thank you in advance!

**Comment by taiyangc** [comment]
Could you elaborate on the rate of frauds/thefts, as we are not aware of any. Some proofs or reports would be great. Thanks.

**Comment by serderovsh** [comment]
Theft is possible only in the case of an online signature and the connection of unreliable nodes

**Comment by cryptozwerg** [comment]
Well, my experience in this comes mostly from the Dapps. Most of them are providing this very prominent model with dividends. Those dividends tokens are rarely (yet) on any DEX and players are trading them mainly in Telegram and Discord groups. That said I've seen ppl loosing up to 1 300 000 TRXs in such "trades" and this is why I cam to the idea, that instead of bot swaping and creating OTC markets and such we could, as community, find a better solution that will cover not only such stupid scenarios, but in general the whole security part of any transaction. Because the botting army is popping already with stolen Twitter accounts asking for confirmation (in lottery alike scheme, pure frauds) with the user sending from 10k to 1kk trx in order to get double of that amount back. You remember these from the ETH chain, right? So, a layer of securitiy against such things could be made in many ways: with delay and swap confirmation, it could be made with signatures , but before all I think that a community driven system ( something similar as the SR system we have) could make it even better.

**Comment by Kondax** [comment]
Hi,
This isn't applicable for TronWeb. TronWeb is developer software to create transactions.
