### ISSUE TITLE
Shasta events timedout

### ISSUE THREAD

**Issue by Zuum** [tronprotocol/tron-web#131]
I know this may be not the best place to open the issue, but I couldnt find better one.

After TRON Shasta maintenance on Dec 18 I can no longer receive events from a smart contract (which i could do before). Keep getting timedout errors.

As I understand its a temporary issue, caused my some migrations on shasta testnet. If it is so, i would like to know when it is supposed to be finished

Contract:
`
contract Game
{
  address public owner;
  // so you can log these events
  event Deposit(address _from, uint _amount);

 constructor() public {
    owner = msg.sender;
  }

  function enterGame() public payable {
    emit Deposit(msg.sender, msg.value);
  }
}
`

Oracle (tronWeb instance is on shasta provider)
`
return tronWeb.contract().at(record.address).then((shnake) => {
      return shnake.Deposit().watch((err, response) => {
          if (err) return console.error('Failed to bind event listener:', err);
          let { result } = response;
          let userAddress = result._from;
          let amount = result._amount;
          return console.log("Deposit:", result);
        }).catch((err) => {
          console.log("Contract event catch error", err);
        }),
})
`

Error:
`
{ Error: timeout of 30000ms exceeded
    at createError (C:\Users\Ilya\WebstormProjects\ShnakeBackend\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (C:\Users\Ilya\WebstormProjects\ShnakeBackend\node_modules\axios\lib\adapters\http.js:216:16)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 30000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.18.0' },
     method: 'get',
     baseURL: 'https://api.shasta.trongrid.io',
     auth: false,
     data: null,
     params: {},
     url: 'https://api.shasta.trongrid.io/event/contract/TJdnwHGhJSWbW8Br7ouQU3rBMMbrhaE8az/Deposit?since=1545233548105&size=20&page=1' },
  code: 'ECONNABORTED',
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { protocol: 'https:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path: '/event/contract/TJdnwHGhJSWbW8Br7ouQU3rBMMbrhaE8az/Deposit?since=1545233548105&size=20&page=1',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        hostname: 'api.shasta.trongrid.io',
        port: null,
        nativeProtocols: [Object],
        pathname: '/event/contract/TJdnwHGhJSWbW8Br7ouQU3rBMMbrhaE8az/Deposit',
        search: '?since=1545233548105&size=20&page=1' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'GET /event/contract/TJdnwHGhJSWbW8Br7ouQU3rBMMbrhaE8az/Deposit?since=1545233548105&size=20&page=1 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: api.shasta.trongrid.io\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/event/contract/TJdnwHGhJSWbW8Br7ouQU3rBMMbrhaE8az/Deposit?since=1545233548105&size=20&page=1',
        _ended: false,
        res: null,
        aborted: 1545233578120,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: [HTTPParser],
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://api.shasta.trongrid.io/event/contract/TJdnwHGhJSWbW8Br7ouQU3rBMMbrhaE8az/Deposit?since=1545233548105&size=20&page=1' },
  response: undefined }
`

Please redirect me to a more relevant repository to repost this question if you find it belong there

**Comment by Kondax** [comment]
TronGrid would be more appropriate; https://github.com/tronprotocol/tron-grid

**Comment by Zuum** [comment]
Thanks
