### ISSUE TITLE
tronWeb return different format when calling contract

### ISSUE THREAD

**Issue by aker0357** [tronprotocol/tron-web#135]
``` 
contract Template {
    function getValue() public view returns(uint abc){
         abc = 1;
    }

    function getValue1() public view returns(uint){
         uint abc = 1;
         return abc;
    }
}

``` 
when you call these two function in tronWeb , you could get different format return value

tronbox(shasta)> contract.getValue().call()
{ abc: BigNumber { _hex: '0x01' } }
tronbox(shasta)> contract.getValue1().call()
BigNumber { _hex: '0x01' }

**Comment by Kondax** [comment]
Use `.toNumber()` on the result
