### ISSUE TITLE
how much energy fee limit should be set ?

### ISSUE THREAD

**Issue by VVILD** [tronprotocol/tron-web#147]
i am trying to call this contract function using tronweb .

let result = await res.fundGooResearch(50000).send({
feeLimit:20000,
callValue:0,
shouldPollResponse:true
});

i have tried with feelimit from 20000 to 100000 i get different errors each time . what should be my feelimit ? how do i make it so that the transaction takes trx and not energy .

these are the errors i get .

error:
   "Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[2000], curOpEnergy[3], usedEnergy[2000]",

 "Not enough energy for 'JUMPI' operation executing: curInvokeEnergyLimit[180], curOpEnergy[10], usedEnergy[179]",

**Comment by Kondax** [comment]
The maximum energy is `1,000,000,000`. I believe the issue you've shown is that your account doesn't have enough energy / trx to cover the call.

I'd recommend heading over to tronprotocol/java-tron.
