### ISSUE TITLE
Equivalent function to web3.BatchRequest() missing?

### ISSUE THREAD

**Issue by errnaa** [tronprotocol/tron-web#148]
I looked at "Proposal for new TronWeb API" which listed "Missing Web3 Functionality" and BatchRequest was not there, suggesting that batching is already implemented. I searched both the "tron-web" Github repository and its API reference at "developers.tron.network" and was unable to find anything related to batching.

I'm not sure whether this is not implemented, undocumented, or was called something else other than batching. Regardless batching seems to be an important features for Dapps that depends on transactions being processed in the correct order, especially since Solidity's "ABIEncoderV2" is not yet released and we are not able to use an array of structs as a parameter.

**Comment by Kondax** [comment]
Batch requests aren't available in TronWeb at the moment. Synchronous requests aren't really an issue since TronWeb offers the use of promises.

I think this could definitely be implemented if you didn't want to await / async yourself.

I'd recommend just doing the following in the mean time:

```js
const results = [
    await someMethod(),
    await someOtherMethod()
];
```

**Comment by errnaa** [comment]
Thanks for the response and recommendation. I'll try that in the mean time.

**Comment by sullof** [comment]
@errnaa 
For better performances, I suggest you call:
```
const results = await Promise.all([
    someMethod(),
    someOtherMethod()
]);
```

**Comment by Kondax** [comment]
@sullof that function will not run them synchronously

**Comment by Kondax** [comment]
@sullof Promise.all will execute them in parallel, not synchronously

**Comment by sullof** [comment]
Yes, but if you have many requests to do and can execute them asynchronously, `Promise.all` makes the process much faster.

**Comment by Kondax** [comment]
They are specifically asking for it to run synchronously :smile:

**Comment by sullof** [comment]
I see.
@errnaa, ignore my comment 😄
