### ISSUE TITLE
Asset id issue

### ISSUE THREAD

**Issue by kookiekrak** [tronprotocol/tron-web#151]
Tronweb should be able to handle asset id's as either numbers or strings. Currently, it only accepts strings.

**Comment by sullof** [comment]
@kookiekrak Can you point me to some method with that issue?

**Comment by sullof** [comment]
I am asking because everywhere we check `utils.isInteger(tokenId)` which produces
```
> tronWeb.utils.isInteger(1222)
true
> tronWeb.utils.isInteger('1222')
true
```
and later we `parseInt(tokenID)`.

**Comment by serderovsh** [comment]
Everything works fine
```javascript
let create_tx = tronWeb.transactionBuilder.sendToken('to_address', 1, '1000317').then(tx => {
      console.log(tx);
})
```

**Comment by kookiekrak** [comment]
@serderovsh that's because you passed it as a string

try this, you'll see it fails

let create_tx = tronWeb.transactionBuilder.sendToken('to_address', 1, 1000317).then(tx => {
      console.log(tx);
})


tronWeb.utils.isString(1000317) == false

**Comment by serderovsh** [comment]
@kookiekrak,

As for me the best option :)
```javascript
       // If we get the id token, we convert to string
        if(utils.isInteger(tokenID))
            tokenID = tokenID.toString();
```

**Comment by serderovsh** [comment]
@sullof, and the structure of api has changed?
‘’’javascript
let create_tx = tronWeb.transactionBuilder.sendToken('to_address', 1, 'IPFS').then(tx => {
      console.log(tx);
})
‘’’
// result no asset?

everything was good before. now only id works

**Comment by sullof** [comment]
@serderovsh That does not work anymore because the name of the token is not unique. You must pass the token id  that is a string like `1000211`
