### ISSUE TITLE
transactionResultManager fails to throw errors

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#153]
@sullof [`transactionResultManager` uses `this.tronWeb`](https://github.com/tronprotocol/tron-web/blob/master/src/lib/transactionBuilder.js#L12) when attempting to decode transaction error messages. the issue with this is that `this` is not in the context of `TransactionBuilder`, therefore it throws `cannot read property tronWeb of this`.

I'd recommend moving `transactionResultManager` into `TransactionBuilder` to become a function. This will fix the issue.

**Comment by sullof** [comment]
@Kondax I can't believe I missed that :-)
I am fixing it...

**Comment by sullof** [comment]
I fixed it at https://github.com/tronprotocol/tron-web/pull/152
Thanks
