### ISSUE TITLE
getTransactionsRelated sorted by timestamp bug

### ISSUE THREAD

**Issue by gutenye** [tronprotocol/tron-web#154]
The response from `gettransactionsfromthis` does not contain timestamp information.
But the tronweb getTransactionsRelated is sorted by timestamp.
https://github.com/tronprotocol/tron-web/blob/master/src/lib/trx.js#L244

```
{
  "transaction": [
    {
      "signature": [
        "d1a52e0c038c6c2d264e761f99e40750a8ed463da03351136145ca6d2db9701483465adfb60fd28f66f4308dc3ba49f0b19c44d5fdb12102424f8abe523ed1af01"
      ],
      "txID": "a6cc308f58bea784ebb6dabe57964b0a1cc82df55e5660cb43ee0b8f76cc6498",
      "raw_data": {
        "contract": [
          {
            "parameter": {
              "value": {
                "amount": 100000,
                "owner_address": "41ad05180b8c85ef1a4eb551f33b4074b29f222bf2",
                "to_address": "4142920bce53cfc039374060e495d6dc9aa2d39fea"
              },
              "type_url": "type.googleapis.com/protocol.TransferContract"
            },
            "type": "TransferContract"
          }
        ],
        "ref_block_bytes": "4aee",
        "ref_block_hash": "5a873a12132402cb",
        "expiration": 1537240284000
      }
    }
  ]
}
```

**Comment by Kondax** [comment]
Timestamp field is optional for transactions. TronWeb sorts by default, as the API doesn't necessarily return transactions in order anyway

**Comment by gutenye** [comment]
@Kondax Thanks for quick replying. 

Is it possible to add timestamp or block_height in the response?

It makes senses that a wallet wants to merge and sort them in a specific order. Otherwise, what's the use case for it if the order is in random.

**Comment by Kondax** [comment]
You can broadcast a transaction with a timestamp, but you cannot access it
if it doesn't include one. You can get the block timestamps with a seperate
call

**Comment by gutenye** [comment]
>  You can get the block timestamps with a separate call

How to do it? 
I don't understand the `ref_block_hash` field, the real block hash is much longer than this.

**Comment by Kondax** [comment]
Get transaction by ID

**Comment by Kondax** [comment]
Get transaction info is the one, my bad. Unsure as to why it's empty - better to head over to java-tron
