### ISSUE TITLE
getTransactionsRelated() always return []

### ISSUE THREAD

**Issue by Ankarrr** [tronprotocol/tron-web#155]
I want to use getTransactionsRelated() to get transactions of a particular account, but I always receive []. I am sure there are some transactions related to my test account.

My code:
```
const txs = await tronWeb.trx.getTransactionsRelated('TBAXGxnGhan2weQH1msgwa4XawGDA98jp9', 'all', 30, 0);
```

**Comment by serderovsh** [comment]
I agree.
Because of this, transactions are not displayed in "TronLink"

**Comment by serderovsh** [comment]
Most likely this is not related to the plugin.

**Comment by Kondax** [comment]
You have had had multiple answers in discord and been told to stop duplicating your question.

Shasta has the walletextension API disabled, so this will always return an empty array.

**Comment by Ankarrr** [comment]
I just want to report this issue to the maintainers of TronWeb. I don't know you are one of them. Really sorry about that.

**Comment by cancerts** [comment]
> I just want to report this issue to the maintainers of TronWeb. I don't recognize you are one of them in Discord. Really sorry about that.

i also come to the question ,and how do you solve it?
