### ISSUE TITLE
Contracts don't use the new error handler

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#156]
Contract broadcasting doesn't use the new error handler, see:

https://github.com/tronprotocol/tron-web/blob/22ad1e445e15f59068d049b8fab1de3b8107843d/src/lib/contract/index.js#L176 and
https://github.com/tronprotocol/tron-web/blob/fc24875f6ddde5d7b3fae5aeec8749239e6aac02/src/lib/contract/method.js#L189

This results in an error similar to:

```
Unknown error: {
  "code": "CONTRACT_VALIDATE_ERROR",
  "message": "636f6e74726163742076616c6964617465206572726f72203a2056616c696461746520496e7465726e616c5472616e73666572206572726f722c2062616c616e6365206973206e6f742073756666696369656e742e"
}
```

Which cannot be parsed easily.

**Comment by sullof** [comment]
@Kondax When you talk about the new handler you refer to...?

**Comment by sullof** [comment]
Found.

**Comment by Kondax** [comment]
The one in transaction builder

**Comment by sullof** [comment]
I fixed it in a different way. Can you take a look at https://github.com/tronprotocol/tron-web/pull/160 ?
