### ISSUE TITLE
address.fromHex doesn't account for TVM addresses

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#157]
There's three types of addresses that are commonly used for TRON:
- Base58, which starts with `T`
- Hex:
  - Which starts with `41` (Network)
  - Which starts with `0x` (TVM)

TronWeb only currently accounts for the `41` prefix in the method `tronWeb.address.fromHex`, which creates a lot of confusion for developers when trying to convert TVM addresses.

A simple solution would be to slice the input address at pos `2` and append the result to `41`:

```js
const fromHex = ambiguousAddress => {
    const hexAddress = `0x${ ambiguousAddress.substr(2) }`;
    return someConversionFunc(hexAddress);
};
```

**Comment by sullof** [comment]
I fixed it in https://github.com/tronprotocol/tron-web/pull/160
