### ISSUE TITLE
how to start web3 http server?

### ISSUE THREAD

**Issue by wndehrdnlgja** [tronprotocol/tron-web#159]
i setup solidity, full node and data synchronization is complete.
RPC communication on the node server was successful.
i'm going to work with C#.
if web3 is supported, Nethereum will make communication easier.
but I don't know how to run the tronweb.
i have finished installing nodejs.
Please give me a detailed guide.

**Comment by sullof** [comment]
This section is for technical issues in TronWeb. For support, post your question in the TronWeb channel in our Discord.
