### ISSUE TITLE
How to Integrate TronWeb into Mobile App

### ISSUE THREAD

**Issue by Hansong9527** [tronprotocol/tron-web#170]
I plan to make a Tron wallet to support tron's DAPP payment function. What do I need to do to enable users to recognize tron's wallet in our app and call my app's wallet payment function? Is there a corresponding development instructions or a packaged JS file that can be injected?

**Comment by serderovsh** [comment]
TronWeb - provides an opportunity to work with the "Tron API" and work with contracts.
On the "github" if several options for purses for "Tron"

https://developers.tron.network/docs/tron-web-intro

**Comment by sullof** [comment]
No. I know that someone is buillding a mobile wrapper for TronWeb, but I don't know when they will release it.
