### ISSUE TITLE
release 2.1.30 version of tronweb on github

### ISSUE THREAD

**Issue by quantumcatwang** [tronprotocol/tron-web#173]
It is better to release 2.1.30 (latest version) of TronWeb, although it has already been done on NodeJS library, but current github release version is still 2.1.5.
Some important module require at least 2.1.24 version, like withdraw, etc.

**Comment by sullof** [comment]
TronWeb is not releasing the final code for months. We removed the section to avoid misunderstanding. It is better, anyway, to install the module locally and copy the `dist/TronWeb.js` file wherever is needed.
