### ISSUE TITLE
Sending TRC10 to a smart contract

### ISSUE THREAD

**Issue by sambengtson** [tronprotocol/tron-web#174]
I'm trying to implement a smart contract that swaps TRC10 tokens.  I am using this guide as a reference:  [url](https://developers.tron.network/docs/trc10-transfer-in-smart-contracts)

I was under the impression that I could set tokenId and tokenValue as shown below, but msg.tokenid and msg.tokenvalue are empty when my smart contract function gets called.  Is this a bug or can somebody show me the correct way to send TRC10 to a payable smart contract function?

```
const contract = await tronWeb.contract().at(contractAddr);
        const result = await contract.tradeToken(1000089).send({
            feeLimit: tronWeb.toSun(100),
            callValue: 0,
            tokenValue: 10,
            tokenId: 1000087,
            shouldPollResponse: true
        });
```

**Comment by sambengtson** [comment]
According to this document, it does not seem possible at this time

https://developers.tron.network/docs/trc10-token

**Comment by taiyangc** [comment]
It should be possible. The link had an outdated comparison chart.

Please check a few things:
1) Are you running it against shasta or a local privatenet? If local please make sure to enable the TRC10 transfer feature
2) Make sure tronweb is up-to-date
3) Make sure the sending account has at least 10 of id = 1000087 TRC10 token

**Comment by sambengtson** [comment]
Hey @taiyangc, thanks for responding

1.  I am running against shasta currently
2.  Got it.  Running latest version from NPM
3.  Account has 10000+ tokens

I mocked up a the smart contract function to make it easier for debugging.  I'm basically just emitting msg.tokenid and msg.tokenvalue.  Both seem to be of value "0".

```
function tradeToken(uint toToken) public payable returns(uint) {
//Just a test to debug values
    emit LogToken(toToken);
    uint fromToken = msg.tokenid;
    emit LogToken(fromToken);
    uint amount = msg.tokenvalue;    
    emit LogToken(amount);
}
```

**Comment by sambengtson** [comment]
Apparently I was using an older version of tron web.  It does work now.  Thank you!

**Comment by shane-jan** [comment]
Hi,

@sambengtson Can you please post the smart contract you used for this purpose? I am having the same problem when trying to swap TRC10 to TRC20.

**Comment by sambengtson** [comment]
@shane-jan  Unfortunately, I can't share the entire smart contract as it's private to a company.  However, if you can share yours, I can probably help debug it.

**Comment by shane-jan** [comment]
@sambengtson Thank you. Here is what I have tried to create. I have given you access to the repository.

https://github.com/shane-jan/trc10-/
