### ISSUE TITLE
Sending TRX

### ISSUE THREAD

**Issue by berar** [tronprotocol/tron-web#175]
I have a contract loaded into an Utils object like: 

`var tronWebUtils = {
    tronWeb: false,
    contract: false,

    async setTronWeb(tronWeb) {
        this.tronWeb = tronWeb;
        this.contract = await tronWeb.contract().at(contractAddress)
    }
};`

That contract in contractAddress has a payable and mutable function called pay(). 

How to invoke it programatically with tronWeb and pay trx?

I know when there's a mutable function, it's going to be like: 

`tronWebUtils.contract.methodName().send()`

**Comment by berar** [comment]
I found out it was tronWebUtils.contract.pay().send({callValue: 0})

Somebody really should add this to examples.

**Comment by Kondax** [comment]
It is documented [here](https://developers.tron.network/reference#methodsend)
