### ISSUE TITLE
Smart contracts can fail with "Invalid issuer address provided"

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#176]
@sullof There's currently an odd "bug" that causes smart contract calls to fail with `Invalid issuer address provided`. This happens if you don't configure TronLink with a default address before initiating smart contracts.

You can see below that the default `from` property is set to `this.tronWeb.defaultAddress.hex`.

https://github.com/tronprotocol/tron-web/blob/be3a41697c663e9985560936b7926afd384c5369/src/lib/contract/method.js#L37

Later on, smart contract methods will apply this default value (if not explicitly defined in the call's options object) and call `tronWeb.toHex(options.from)`. 

https://github.com/tronprotocol/tron-web/blob/be3a41697c663e9985560936b7926afd384c5369/src/lib/contract/method.js#L102

If `options.from` happens to be `false`, this will cause `toHex` to output `0x0`. This then means that the `triggerSmartContract` function will receive `0x0` for the address, which isn't a falsy value as it's a string.

https://github.com/tronprotocol/tron-web/blob/278f06f187dcc82b052991be0d75898fd594be48/src/lib/transactionBuilder.js#L447

Calling `tronWeb.isAddress("0x0")` will return `false`, triggering the `Invalid issuer address provided` error mentioned above.

This won't only be an issue with TronWeb instances that are created without a default address, it will also cause issues if you change the default address after calling `tronWeb.contract()`. This is because Javascript will cache `this.tronWeb.defaultAddress.hex` and not evaluate the line each time a smart contract method is called. You can see a more clear example below:

```js
const defaultOptions = {
	from: 'test'
};

const options = {
	from: defaultOptions.from
};

const someFn = () => `Address: ${ options.from }`;

defaultOptions.from = 'qwerty';

console.assert(someFn() === `Address: ${ defaultOptions.from }`)
```

Running the above will fail the assertion, as `defaultOptions.from` has already been evaluated and cached.

**The simplest solution would be to not use a default value, but instead pass `false` if `options.from` is not explicitly set.** This will then correctly default to `tronWeb.defaultAddress` at time of execution in the `triggerSmartContract` function.

**Comment by sullof** [comment]
Thanks. I will work on it asap.

**Comment by sullof** [comment]
This is not fully fixed and I am reopening it.

**Comment by shenyongri110** [comment]
@ProtonGustave Thanks for your fix, the branch has been merged, so close it.
