### ISSUE TITLE
Tron-web integrate to Laravel Project

### ISSUE THREAD

**Issue by Vilayhong** [tronprotocol/tron-web#184]
Hi. 
I am going to make trading platform that run on tron blockchain.
So I was going to integrate tron-web to my laravel project.

I was going to do it my self.
my work flow is below.

Create new laravel project in my local Pc.(laravel version is 5.7)

And I installed tronweb with  "npm install tronweb".

![package json](https://user-images.githubusercontent.com/40490778/52833639-5661d280-3110-11e9-9ef7-fcba606903d9.png)

And I made tron_trading.js file and added it to app.js file.
trading.js
*********************************======================*********************
import TronWeb from 'tronweb';

const HttpProvider = TronWeb.providers.HttpProvider;
const fullNode = new HttpProvider('https://api.shasta.trongrid.io'); // Full node http endpoint
const solidityNode = new HttpProvider('https://api.shasta.trongrid.io'); // Solidity node http endpoint
const eventServer = 'https://api.shasta.trongrid.io'; // Contract events http endpoint
const privateKey = 'xxxx';

const tronWeb = new TronWeb(
    fullNode,
    solidityNode,
    eventServer,
    privateKey
);
console.log("tron js loaded");

const getbalance = async function getBalance() {
    const address = 'TLfKZemuDA8D6JLhQjJno614hGVLaSxamJ';
    console.log(address);

    balance  = await tronWeb.trx.getBalance(address);
    console.log("Get My trx balance");
    console.log(balance);

};

******************************=====================**************************

And app.js included it as below.
![image](https://user-images.githubusercontent.com/40490778/52833719-bbb5c380-3110-11e9-93cd-deab35f5f2a1.png)

but I got this error and issues on web console.

![image](https://user-images.githubusercontent.com/40490778/52839109-84064600-3127-11e9-8398-0ec4fd4c9507.png)

I want to get balance.
Please help me.
Thanks and Regards.

**Comment by 1099511627776** [comment]
I dont think its a problem of tronWeb. I'm using laravel with tronweb myself and never saw this kind of problem. I think its in your code. If you publish your code (may be in private repository) may be i'd look through it when have time.

**Comment by Kondax** [comment]
Looks like an issue with either your own network or TronGrid. Please don't publish your private keys.

**Comment by Vilayhong** [comment]
thanks for your help.
do you have a laravel template with tron-web?

**Comment by Vilayhong** [comment]
Hi 1099511627776?
Could you send me your template laravel code?

**Comment by 1099511627776** [comment]
Unfortunately no. It is already in production project. If you publish your template that i'll try to look at it
