### ISSUE TITLE
getTransactionsFromAddress doesn't work

### ISSUE THREAD

**Issue by KirillKirill** [tronprotocol/tron-web#186]
It returns 405 error

**Comment by KirillKirill** [comment]
And this:
Access to XMLHttpRequest at 'https://api.shasta.trongrid.io/walletextension/gettransactionsfromthis' from origin 'http://localhost:63342' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Kondax** [comment]
I believe these endpoints were disabled, or there's some other issue with TronGrid. This isn't applicable to TronWeb.
