### ISSUE TITLE
How to watch my account for transactions

### ISSUE THREAD

**Issue by stone89son** [tronprotocol/tron-web#187]
Hi.
I am looking for an example of checking transactions that occur on my account. 
Clarification: I am building a trading platform. When a user orders a Buy token, they will have to send TRX to my TRONX account. The part I'm building is getting that realtime order information via TRONX account and adding it to the database.

Thank for reply.

**Comment by khanhnd69** [comment]
You can watch new blocked (10s) in real time. Read block to get transaction hash, then get transaction info, if your account have in each transaction data, you will update to database.

**Comment by stone89son** [comment]
@khanhnd69 Can you give me an example or link for reference?

**Comment by haidt18** [comment]
@stone89son If you have only 1 account that will received TRX from user, then you can use getTransactionsToAddress functions to get all txs thats destination if your account, if you have many destination, it wi be more effective to use @khanhnd69  method.
tronweb api : https://developers.tron.network/reference

**Comment by haidt18** [comment]
> You can watch new blocked (10s) in real time. Read block to get transaction hash, then get transaction info, if your account have in each transaction data, you will update to database.

new block actually happen at 4-5 seconds.

**Comment by sullof** [comment]
There is a new block every 3 seconds.
Anyway, this is not an issue. If you need support, post a request in our Discord group.

**Comment by stone89son** [comment]
> @stone89son If you have only 1 account that will received TRX from user, then you can use getTransactionsToAddress functions to get all txs thats destination is your account, if you have many destination, it wi be more effective to use @khanhnd69 method.
> tronweb api : https://developers.tron.network/reference

request continuously check new transaction is not good, Is there a better way? Does tronx block games do the same?

**Comment by stone89son** [comment]
> There is a new block every 3 seconds.
> Anyway, this is not an issue. If you need support, post a request in our Discord group.



> There is a new block every 3 seconds.
> Anyway, this is not an issue. If you need support, post a request in our Discord group.

Thank, i will join Discord group
