### ISSUE TITLE
Send TRC20 token?

### ISSUE THREAD

**Issue by CryTrExcom** [tronprotocol/tron-web#190]
How to transfer TRC20 token from one address to another with tronweb?

Thanks

**Comment by haidt18** [comment]
@CryTrExcom use this one 
`const fullNode = new HttpProvider("https://api.trongrid.io"); // Full node http endpoint
const solidityNode = new HttpProvider("https://api.trongrid.io"); // Solidity node http endpoint
const eventServer = new HttpProvider("https://api.trongrid.io")

const tronWeb = new TronWeb(fullNode, solidityNode, eventServer);
const tx = await tronWeb.trx.sendToken(
      _to,
      _amount,
      _tokenId
    );`

**Comment by CryTrExcom** [comment]
This is for TRC10

**Comment by haidt18** [comment]
> This is for TRC10

yes you are right.

**Comment by CryTrExcom** [comment]
but we ask for TRC20 tokens, we know how to transfer TRC10

**Comment by haidt18** [comment]
sorry i didnt know it too, have you tried send via tronWeb.transactionBuilder.sendToken()?

**Comment by CryTrExcom** [comment]
on demo.js is see this

`    tronWeb.transactionBuilder.triggerSmartContract(
        '413c8143e98b3e2fe1b1a8fb82b34557505a752390',
        'multiply(int256,int256)',
        30000,
        0,
        [
            { type: 'int256', value: 1 },
            { type: 'int256', value: 1 }
        ],
    (err, transaction) => {
        if(err)
            return console.error(err);
    
        console.group('Unsigned trigger smart contract transaction');
            console.log('- Contract Address: 413c8143e98b3e2fe1b1a8fb82b34557505a752390');
            console.log('- Transaction:\n' + JSON.stringify(transaction, null, 2), '\n');
        console.groupEnd();
    });
`
but how to define receiver address, i see contract address on hex, amount but the receiver?

**Comment by ProtonGustave** [comment]
@CryTrExcom just use _transfer_ method.
`const contract = await tronWeb.contract().at('<contract_address>');
contract.transfer('<to_address>', <tokens>).send()`
[tronweb docs](https://developers.tron.network/reference#methodsend)
