### ISSUE TITLE
Mistake in documentation of transactionBuilder.sendTrx and trx.sendTransaction methods

### ISSUE THREAD

**Issue by ProtonGustave** [tronprotocol/tron-web#195]
[here](https://developers.tron.network/reference#sendtrx) and [here](https://developers.tron.network/reference#sendtransaction)
Description of _amount_ param is 

> Amount of TRX to send.

But this is amount of SUN to send, not TRX.

**Comment by sullof** [comment]
You can suggest the correction on the developer.tron.network website.
Reporting the issue here is not helpful. 
Anyway, I will forward it to the people who manage the documentation.

**Comment by tmao1129** [comment]
@ProtonGustave Hi Sergey, the Developer Documents have been updated here: https://developers.tron.network/reference#sendtrx and https://developers.tron.network/reference#sendtransaction. Thank you for raising the issue, and next time please let us know directly by suggesting edits in the documentation itself. Thank you!
