### ISSUE TITLE
Can't receive event on shasta

### ISSUE THREAD

**Issue by micahli** [tronprotocol/tron-web#203]
My server couldn't receive event from yesterday, don't know what happened. It did well before.
I can call the auth() method and the contract will emit an Auth event. The transaction is finished and
i can find the event record on https://api.shasta.trongrid.io/event/contract/TRxxxxxxxx
however in my serverside, the watch method is not called. My event watch code is below:
tronWeb.contract().at(gameContractAddress).then(ctr=>{
        if (ctr == null) {
            console.error("fail to get game contract");
        } else {
            console.log("game contract loaded");
            gameContract = ctr;

            // User Auth event
            gameContract.Auth().watch((err, arg)=>{
                //console.log("user auth: ", err, arg);
                if (err == null && arg) {
                    authHandler(arg);
                }
            });
.......

can anyone help?   Thanks!

**Comment by czl1378** [comment]
same issue

**Comment by czl1378** [comment]
Hey, have you solved it?

**Comment by micahli** [comment]
I could receive events after i updated the tronweb library. But another
problem appeared, all the events will be sent to my watch method about
every two minutes or longer. I haven't touch TRON for one week, i don't
know what has changed in last week.
