### ISSUE TITLE
How can I get method calling data from a transaction?

### ISSUE THREAD

**Issue by superalex88** [tronprotocol/tron-web#207]
Hi when I call the getTransactionInfo (this transaction is a bout a smart contract function calls) method the information returned are like this:

`{ id:
   '9f5787bc891f786e228fa4391d7af9d9ce8874c4d29014501a47fefaabfe9bf4',
  blockNumber: 2068222,
  blockTimeStamp: 1552053165000,
  contractResult: [ '' ],
  contract_address: '411f80cfc641f214fe6ce66d043ca25ee76c1b968e',
  receipt:
   { energy_usage: 492,
     energy_usage_total: 492,
     net_usage: 379,
     result: 'SUCCESS' } }`

But if I search with tronscan I get also the Method calling info: Contract Method name called and data passed as parameter.

It is possible to get this info in some way or i missing something?

thanks

**Comment by sullof** [comment]
We don't manage TronScan. Most likely it is a problem in the way they retrieve the data.
