### ISSUE TITLE
Tron-eventquery API support

### ISSUE THREAD

**Issue by ProtonGustave** [tronprotocol/tron-web#210]
Will tronweb support tron-eventquery API(tronex)? Because it's better than tron-grid. I'll modify tronweb for myself to support tronex, i don't know should i PR this changes.

**Comment by sullof** [comment]
TronWeb is not going to support that API right now and a PR adding that would probably be declined. Although, we added in https://github.com/tronprotocol/tron-web/pull/201 a plugin architecture that can allow the integration of external libraries in TronWeb. To make it more flexible I am moving the Events out of the primary class, in a subclass. As soon as that is ready, you could create a plugin that adds support for the tron-eventquery.
About tronex, what do you mean?
I took a look at Tronex API and it seems to me that it returns a format incompatible with any dApp currently using TronWeb for the events. 
Also, the average response time is very high. If you compare
https://api.tronex.io/events/TEEXEWrkMFKapSMJ6mErg39ELFKDqEs6w3
with 
https://api.trongrid.io/events/contract/TEEXEWrkMFKapSMJ6mErg39ELFKDqEs6w3
you see that the first never returns data in less than 200 ms, while the second returns data in an average of 30 ms.
Moreover, there is no history at all. If TronGrid should return only the very recent events, it would return the data in 5 ms.
