### ISSUE TITLE
 tronWeb.trx.getTransactionsRelated is on work 

### ISSUE THREAD

**Issue by cancerts** [tronprotocol/tron-web#223]
```
 tronWeb.trx.getTransactionsRelated('TGEJj8eus46QMHPgWQe1FJ2ymBXRm96fn1', 'all').then(transactions => {
        console.group('Transactions relating to address');
            console.log('- Address: TGEJj8eus46QMHPgWQe1FJ2ymBXRm96fn1');
            console.log('- Transactions:\n' + JSON.stringify(transactions, null, 2), '\n');
        console.groupEnd();
    }).catch(err => console.error(err));
```

**Comment by sullof** [comment]
The method in TronWeb is working. The problem with the results depends on the Solidity Node you connect to. If you are using TronGrid, for example, the `/walletextension` are not supported and that will return an error.
Can you provide me with more details, please?

**Comment by sullof** [comment]
I saw https://github.com/tronprotocol/tron-web/issues/222. I guess it is the same issue. I am closing this one too.
