### ISSUE TITLE
trx.getBlock not working stable

### ISSUE THREAD

**Issue by haidt18** [tronprotocol/tron-web#229]
Hello,
i need help, i used the funtion `trx.getBlock` form tronweb js lib for getting real time tx so that I can filter it based from its params, app work well but today the getting block data seem not stable, some block can get data, some cant
is there any breaking change regarding to the tronweb library recently but before the block 7622584, it works fine ?
please check our log from here : https://cl.ly/2918d48e649c you can see some block it can get tx, some cant
thanks

**Comment by sullof** [comment]
This is not an issue with TronWeb, but with the fullNode you are connected to.

**Comment by haidt18** [comment]
hi @sullof , please dont close this issue, I connected to https://api.trongrid.io not my own fullNode,  I have tried to run app on another server, it works fine,  some one told me that I got rate limit request, but I cant find any document from tronweb which mentioned about this? my had been running fine until yesterday! is there any breaking change in tronweb policy?

**Comment by sullof** [comment]
TronWeb is just an interface to access the HTTP API returned by the Tron Virtual Machine. Specifically, TronGrid works as a proxy towards a full node and has no real control on whatsoever is returned by the full node. If there is an issue with the data returned by the full node, that is a problem of the node, not a TronWeb issue and there is very little we can do on this side.

**Comment by sullof** [comment]
BTW, TronGrid does not set any restriction to the access, so there is not rate limit.

**Comment by haidt18** [comment]
hi @sullof , thanks for your reply, my app called `trx.getBlock` every 5 seconds so around 12 times/minute, some request return block data, some return null. If i run code on another pc, it works fine, do you have any suggestion on this case? thanks alot!

**Comment by sullof** [comment]
I think that you should emit events and watch the emitted events instead of loading all the transactions in a block in order to filter the one you are interested in. The second is a very inefficient and error-prone approach. The first, instead, returns result very fast and is reliable.

**Comment by haidt18** [comment]
hi @sullof , thanks for your suggestion, I have checked that the https://api.trongrid.io is working normally now without any modification. In my scenario I have quite many accounts to watch, if I go for emit event, could you please give me some keywords so that I follow that direction, your help is very appreciated!
