### ISSUE TITLE
How to find the version of tronweb, I feel that you don't 

### ISSUE THREAD

**Issue by ZacharyLe** [tronprotocol/tron-web#231]
How to find the version of tronweb ? I feel that you don't expose to outside of tronweb object.

**Comment by peterbelmont** [comment]
You should use :  "tronweb": "github:tronprotocol/tron-web"

in your package.json to always get latest version.

Check https://www.npmjs.com/package/tronweb to find version. ( currently 2.3.5 )

**Comment by sullof** [comment]
In TronWeb ^2.3.0 you can just check
```
TronWeb.version
```
