### ISSUE TITLE
Event method typo

### ISSUE THREAD

**Issue by hiendv** [tronprotocol/tron-web#232]
I think it should be `getEventsByContractAddress` instead of `getEventsByContactAddress`
https://github.com/tronprotocol/tron-web/blob/69ad4cf40c4026911abbd5c3eb8e985b495ab5b8/src/lib/event.js#L29

**Comment by sullof** [comment]
Thanks a lot. I am fixing it.

**Comment by sullof** [comment]
Fixed in 2.3.6. Thanks.

**Comment by hiendv** [comment]
Thanks but I think it's a breaking change because the API changed. It's a bug fix but it's should be 2.4.x
