### ISSUE TITLE
How to get info of Token and send it

### ISSUE THREAD

**Issue by bachlongkocanh** [tronprotocol/tron-web#239]
I create TRON wallet, i want get info and send token of TRON network. how to do it?

**Comment by haidt18** [comment]
You can use tronweb.trx.getTokenFromID (tokenId)

**Comment by bachlongkocanh** [comment]
@haidt18 What is `tokenId`, can i get info from address token like `eth`?

**Comment by haidt18** [comment]
Unfortunately I didnot see tronweb provide any way to get id(or I don't know), but you can see the token Id mannually from tronscan

**Comment by sullof** [comment]
This depends on the wallet you are using. It is unrelated with TronWeb.
