### ISSUE TITLE
sorting from api incorrect, help please

### ISSUE THREAD

**Issue by zero24x** [tronprotocol/tron-web#248]
hello @developers. please help, it seems the api does return the sortingincorrect now?https://api.trongrid.io/event/contract/THtNSr6rjHtc1hhRQ4Tg9GhBdh3dbjXjxX?fromTimestamp=1553465979000&sort=block_timestamp

i would expect new ones on top but it seems to be mixed old and new, what to do?

**Comment by sullof** [comment]
@zero24x Thanks. That is a bug in TronGrid. I will work on it.

**Comment by sullof** [comment]
@zero24x Fixed. Thanks again for reporting it.

**Comment by zero24x** [comment]
thanks @sullof for the quick response and fix!
