### ISSUE TITLE
not showing the balance of the live net..

### ISSUE THREAD

**Issue by shweta037** [tronprotocol/tron-web#25]
const fullNode = new HttpProvider('https://api.trongrid.io:8090');
const solidityNode = new HttpProvider('https://api.trongrid.io:8091');
const eventServer = 'https://api.trongrid.io/';

using this getting balance 0 for the address THiJqWJQWG9ivNjZQwQFtzcwSt7V3zxbiD

**Comment by shweta037** [comment]
> That node is on a private testnet.

Can you please help me for the main net ....i donot have nay idea...

**Comment by haidoan** [comment]
@shweta037  didn you find fullnode and solidity's ip node that work for then mainnet?

**Comment by serderovsh** [comment]
http://13.125.210.234:8090 - full node

**Comment by haidoan** [comment]
@serderovsh thanks, i got it work by 
const fullNode = new HttpProvider('http://13.125.210.234:8090');
const solidityNode = new HttpProvider('http://39.105.66.80:8091');
const eventServer = 'https://api.trongrid.io/';
from [#1](https://github.com/tronprotocol/tron-web/issues/1)

**Comment by kookiekrak** [comment]
We're migrating api.trongrid.io to mainnet on 10/8th
