### ISSUE TITLE
什么时候有最新的Release版本支持TRC10，支持BTT呢？

### ISSUE THREAD

**Issue by zhjing03** [tronprotocol/tron-web#251]
我们发现你们master分支现在支持TRC10 BTT的相关操作，但是最新的Release版本（2.1.5）确不支持，什么时候才能有支持TRC10的Release版本呢？

We found that your master branch now supports TRC10 BTT related operations, but the latest Release version (2.1.5) does not support, when will there be a Release version that supports TRC10?

**Comment by sullof** [comment]
TronWeb release versions long time ago. I just removed them, now, to avoid misunderstandings.
Then easiest way to use TronWeb in a browser is to install it as 
```
npm i tronweb
```
and copy the dist file to your working folder. For example:
```
cp node_modules/tronweb/dist/TronWeb.js ./js/tronweb.js
```
so that you can call it in your HTML page as
```
<script src="/js/tronweb.js"><script>
```
