### ISSUE TITLE
TypeError: Cannot read property 'tronWeb' of undefined

### ISSUE THREAD

**Issue by john-zh** [tronprotocol/tron-web#257]
I think you made a mistake which you already fixed a long time ago.
https://github.com/tronprotocol/tron-web/blob/2be69a0e1870f90fe95195e2b7b60dfb3a0feda8/src/lib/transactionBuilder.js#L24

**Comment by sullof** [comment]
@john-zh What do you mean?

**Comment by john-zh** [comment]
@sullof Just check this line. `this.tronWeb` is undefined if this function is out of the class.

**Comment by sullof** [comment]
You are right. I wonder how this can be back...

**Comment by sullof** [comment]
Fixed. Thanks.
