### ISSUE TITLE
Mapping node outputs

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#26]
Do we want to map node outputs? `TronWeb` uses camelCase with "proper" names, as opposed to the TRON API which uses snake_case and some poorly translated names. Take for example the output of `tronWeb.trx.getAccount()`:

```js
{
  "address": "41612887530b14cb407930c64282769d52016c3217",
  "balance": 10041283245,
  "create_time": 1537832499000,
  "latest_opration_time": 1537842486000,
  "free_net_usage": 23381250135,
  "latest_consume_free_time": 1537842486000,
  "account_resource": {
    "latest_consume_time_for_energy": 1537842486000
  }
}
```

We could instead map this to:

```js
{
  "address": "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY",
  "balance": 10041283245,
  "firstSeen": 1537832499000,
  "lastTransaction": 1537842486000,
  "freeBandwidth": 23381250135000
}
```

I'm not actually sure what `latest_consume_free_time` or `latest_consume_time_for_energy`, but imagine appropriate names that actually describe their values for those too.

**Comment by kookiekrak** [comment]
maybe lets leave it for now, would add confusion for devs moving from blockchain integrations to tronweb implementation. also, these names should be fixed in a /v2 of the httpapi

**Comment by Kondax** [comment]
Sounds good.
