### ISSUE TITLE
TRC20 Coin - how to send TRC20 token as a user to a DApp on the web browser, if TRC20 token does not support ApproveAndCall()

### ISSUE THREAD

**Issue by pkdcryptos** [tronprotocol/tron-web#267]
Hi

I am developing a dApp and failed to understand on how to receive TRC20 coin from user to my dApp, especially if TRC20 token does not support ApproveAndCall().

Then will it be 2 step process ? Like web user need to call tokenContrat.approve() & followed by dAppContract.function that calls tokens tranferFrom on the coin contract ?

TRC223 standard provides ApproveAndCall, but lot of TRC20 coins does not have ApproveAndCall that one quick interface that helps to achieve this goal.

Thanks in advance for any help from experts.

Peter

**Comment by sullof** [comment]
If you try to transfer a standard token but the token does not respect the standard, I am afraid that you will fail. Because you cannot force a transfer if the contract (the erc20 token) does not support that call.

**Comment by pkdcryptos** [comment]
Thanks alot sullof. Appreciate your reply.
