### ISSUE TITLE
How to broadcast a signed transaction without exposing private key?

### ISSUE THREAD

**Issue by coinnect-project** [tronprotocol/tron-web#268]
I have web server that need to send some transactions, but tronweb docs warns about not using sendTransaction and sign functions because they will expose the private key...so I found this guide https://developers.tron.network/docs/transaction which seems to resolve the problem since creates and signs transactions offline but it not explaines how to make the last step that is "After successfully running these functions, you will have a signed transaction that can be broadcasted to the TRON blockchain." 
I tried with the 'tronWeb.trx.sendRawTransaction(signedTransaction)' function passing the signedTransaction of the example as parameter but I get the "Transaction is not signed" error...
So I don't understand what is the right way to create,sign and broadcast a transaction if i have to use my own private key but don't want to expose it but I wasnt able to get the correct answer from documentation.

Thanks

**Comment by shenyongri110** [comment]
@coinnect-project You should make sure the input 'signedTransaction' param has a signature value inside, otherwise it's not a signed transaction. You also can find some sample for creating, signing and broadcasting workflow. Please refer to 'describe("#broadcast"' in https://github.com/tronprotocol/tron-web/blob/master/test/lib/trx.test.js.

**Comment by coinnect-project** [comment]
> #broadca

@shenyongri110 If I use the method tronWeb.trx.sign like in your test then the sendRawTransaction or broadcast it works but, as you say in the docs, the private key will be exposed. Am I right?...so what is the alternative way to do the same operations without letting private key exposed?
I supposed I have to use the TransactionUtils.buildTransferTransaction then the CryptoUtils.signTransaction(privateKey, transaction) methods but I miss what should be the last step since using the sendRawTransaction /broadcast does not work...

**Comment by sullof** [comment]
@coinnect-project If you use tronWeb to sign and broadcast you are not exposing any private key. It has built the way it is exactly to avoid exposing the private key.

**Comment by sullof** [comment]
I am closing this issue because it is not an issue but a misunderstanding of the way tronWeb signs transactions. Feel free to add more comments, if you need.

**Comment by shenyongri110** [comment]
@coinnect-project We will do signature internally inside tronWeb by algorithm instead of using any Java-Tron http api, so tronWeb won't expose any private key.

**Comment by coinnect-project** [comment]
> I am closing this issue because it is not an issue but a misunderstanding of the way tronWeb signs transactions. Feel free to add more comments, if you need.

it was a misunderstanding but I didn't find any other place to ask questions....
Anyway I'm happy that I got an answer but if you warn in docs that a method will expose the key I think is justifiable if some doubts arise 😉

**Comment by sullof** [comment]
@coinnect-project I don't understand. We suggest everywhere to use TronWeb to sign transaction to avoid exposing the private key. Which documentation are you tallking about?

**Comment by coinnect-project** [comment]
@sullof https://developers.tron.network/reference#sign there for example. Maybe you meant something else but was enough to make me think about the problem
