### ISSUE TITLE
fromSun always 0

### ISSUE THREAD

**Issue by vkural** [tronprotocol/tron-web#27]
fromSun method is always giving 0.

I think the problem is trx parameter.  The sun parameter must be passed. **TronWeb.toBigNumber(trx)** 

    static fromSun(sun) {
        const trx = TronWeb.toBigNumber(trx).div(1_000_000);        
        return utils.isBigNumber(sun) ? trx : trx.toString(10);
    }

**Comment by Kondax** [comment]
Fixed in #30 @kookiekrak

**Comment by kookiekrak** [comment]
released as part of 2.0.13
