### ISSUE TITLE
What is the Test Node URL

### ISSUE THREAD

**Issue by wuno** [tronprotocol/tron-web#38]
When working with TronWeb in my JavaScript application I have seen in the example code that these URLs are avaialble. I have also been able to connect and use the API by making a minor adjustment to the code examples. 

```
import TronWeb from 'tronweb';

const fullNode = new HttpProvider('https://api.trongrid.io:8090');
const solidityNode = new HttpProvider('https://api.trongrid.io:8091');
const eventServer = 'https://api.trongrid.io/';
const privateKey = 'SomePrivateKey';
const tronWeb = new TronWeb(fullNode, solidityNode, eventServer, privateKey);

console.log(tronWeb.trx.getBalance(address));
```

1. The docs say to use, `tronWeb.getBalance() `but in JavaScript you actually have to do, `tronWeb.trx.getBalance()`. I wanted to make sure that was known so the docs could be updated. 

2. Also, **what is the correct URL for accessing the test net**? I have not been able to find that in the documentation. 

3. When using the TronWatch desktop wallet I noticed that you can change the URL for the node you want to access. The default is **https://api.tron.watch**, what is the correct URL for the Test Node?

**Comment by kookiekrak** [comment]
Hi @wuno 

1) the TronWeb.getBalance() is old documentation for tronweb 1.x

We've documented the 2.x tronweb api here
https://developers.tron.network/v1.0/docs/tron-web-intro
https://developers.tron.network/v1.0/reference#tronwebapi

2) TRON has two testnets currently, the original unnamed testnet which you would need to run a node to connect to, or the new "Shasta" testnet, with more information here https://www.trongrid.io/shasta/.

3) api.tron.watch is a mainnet node run by the tronwatch team.

if you want to use Shasta testnet, use https://api.shasta.trongrid.io

**Comment by wuno** [comment]
thanks a ton @kookiekrak 

I will give this new information a shot. Super exciting I appreciate all your hard work!

**Comment by sullof** [comment]
@wuno The test api is changed. Use now this:
```
const fullNode = 'https://api.shasta.trongrid.io';
const solidityNode = 'https://api.shasta.trongrid.io';
const eventServer = 'https://api.shasta.trongrid.io/';
```
