### ISSUE TITLE
tronWeb.toHex return different hex then in docs

### ISSUE THREAD

**Issue by kolya182** [tronprotocol/tron-web#53]
@sullof Hi
Regarding docs http://doc.tron.network/en/#tronweb-tohex-str
```js
const t = tronWeb.toHex('TT67rPNwgmpeimvHUMVzFfKsjL9GZ1wGw8');
```
Should return `41BBC8C05F1B09839E72DB044A6AA57E2A5D414A10` instead of i get `0x5454363772504e77676d7065696d7648554d567a46664b736a4c39475a3177477738` same result on local machine as well.

<img width="632" alt="screenshot 2018-10-23 13 20 52" src="https://user-images.githubusercontent.com/3277207/47388250-9404a080-d6c6-11e8-98cf-f5181093d494.png">

```js
var TronWeb = require("tronweb")
 
const HttpProvider = TronWeb.providers.HttpProvider; // This provider is optional, you can just use a url for the nodes instead
const fullNode = new HttpProvider('https://api.trongrid.io'); // Full node http endpoint
const solidityNode = new HttpProvider('https://api.trongrid.io'); // Solidity node http endpoint
const eventServer = 'https://api.trongrid.io/'; // Contract events http endpoint
 
const privateKey = 'da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0';
 
const tronWeb = new TronWeb(
    fullNode,
    solidityNode,
    eventServer,
    privateKey
);

console.log(tronWeb.toHex('TT67rPNwgmpeimvHUMVzFfKsjL9GZ1wGw8'))
```

**Comment by kookiekrak** [comment]
@kolya182 you're decoding an address, please use tronWeb.address.toHex('TT67rPNwgmpeimvHUMVzFfKsjL9GZ1wGw8')

**Comment by kolya182** [comment]
@kookiekrak Couldn't find this in docs, can you update docs ?

**Comment by kookiekrak** [comment]
will do! sorry about that @tmao1129

**Comment by kolya182** [comment]
@kookiekrak Having another issue, this address from docs https://www.trxplorer.io/address/TT67rPNwgmpeimvHUMVzFfKsjL9GZ1wGw8#/transfersOut has `0` outgoing transactions but `curl -X POST https://api.trongrid.io/walletextension/gettransactionstothis -d '{"account" : {"address" : "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}, "offset": 0, "limit": 10}' | json_pp` will return bunch of them do you know what are they ?

**Comment by kookiekrak** [comment]
those two addresses dont match up. the correct trxplorer one should be

https://www.trxplorer.io/address/TWsm8HtU2A5eEzoT8ev8yaoFjHsXLLrckb#/

use this tool, https://tronscan.org/#/tools/tron-convert-tool

to convert base58check to hex

**Comment by kookiekrak** [comment]
btw which docs are you looking at? looks like we have some issues to fix in it

use this one for now
https://developers.tron.network/docs/tron-web-intro

**Comment by sullof** [comment]
@kolya182 
Sorry for my late response, I am sick.

You are using the wrong API.

```
tronWeb.toHex('TT67rPNwgmpeimvHUMVzFfKsjL9GZ1wGw8')
``` 
converts generic data to an exadecimal string.

You want to use:
```
tronWeb.address.toHex('TT67rPNwgmpeimvHUMVzFfKsjL9GZ1wGw8')
```

which produces
```
41bbc8c05f1b09839e72db044a6aa57e2a5d414a10
```

**Comment by tmao1129** [comment]
@kookiekrak  I have added the note in the TronWeb HTTP API section of the Developers Hub: https://developers.tron.network/v1.0/reference#tohex

**Comment by tmao1129** [comment]
@kolya182  Sorry for the inconvenience. We are in the process of consolidating the documentation and deprecating doc.tron.network as well as wiki.tron.network. Moving forward, please refer to developers.tron.network as the official documentation. If you have any documentation questions please feel free to pm me, and also join the developers discord channel: https://discord.gg/GsRgsTD. Thx

**Comment by kolya182** [comment]
@tmao1129 I will, thanks for the link
