### ISSUE TITLE
Improve /wallet/totaltransaction speed

### ISSUE THREAD

**Issue by kolya182** [tronprotocol/tron-web#59]
https://api.trongrid.io/wallet/totaltransaction takes `~40 seconds` to return number of transactions, any way to get in down to `<1sec`

**Comment by Kondax** [comment]
Unfortunately not. This would be better suited for @tronprotocl/java-tron.

**Comment by serderovsh** [comment]
There is one option, I use it.
```
https://api.tronscan.org/api/stats/overview
```
And pull only the last element.

**Comment by Kondax** [comment]
That is a proprietary API for TronScan, which is not supported by TronWeb

**Comment by serderovsh** [comment]
I suggested as an alternative! If the author of the topic does not want to wait 40 seconds
