### ISSUE TITLE
Replace node-signing with local signing

### ISSUE THREAD

**Issue by metjm** [tronprotocol/tron-web#6]
https://github.com/tronprotocol/tron-web/blob/49fd1f2ddbe82f171e7965bd6426ffdb4209c440/src/index.js#L155

There is no reason to ever use http connection for this, its risky and completely unnecessary because the local signing function is already available 2 lines above.

**Comment by lizhengwei1989** [comment]
We only provide another methed to sign by http service, user can use it.Of course it is used  the local signing defaut,if you do nothing.

**Comment by kookiekrak** [comment]
@lizhengwei1989 lets delete the node signing, its unsafe to offer because it will send a private key over the network

**Comment by Kondax** [comment]
Expanding on this, any methods that send the private key or password over http plaintext should be stripped. These can all be achieved locally.

**Comment by lizhengwei1989** [comment]
Okey , it is as you say , I will delete that judge , user can only sign in client without http service.

**Comment by Kondax** [comment]
Closed in #9
