### ISSUE TITLE
Error trapping

### ISSUE THREAD

**Issue by serderovsh** [tronprotocol/tron-web#72]
Hi, "API" lately often began to appear errors in html.
Can you convert them to json format?

```html
<h1><strong>nginx error!</strong></h1>
        <div class="content">
            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>
       </div>
```

Solidity Node: https://api.trongrid.io

**Comment by serderovsh** [comment]
Python: DEBUG - https://api.trongrid.io "POST /walletextension/gettransactionstothis HTTP/1.1" 502 3708
TronWeb: (node:17400) UnhandledPromiseRejectionWarning: Error: Request failed with status code 502

**Comment by Kondax** [comment]
To be honest error handling is an absolute mess right now. The error you're seeing is from a load balancer for TronGrid.

TRON has no standard for errors. There's probably about 5 different ways in which the API returns errors, and sometimes it also returns them despite a request being 200. I can look into "converting" the TronGrid HTML errors into JSON but it still leaves the error mess that the TRON HTTP API has.

**Comment by serderovsh** [comment]
I have already solved the problem.

**Comment by serderovsh** [comment]
> To be honest error handling is an absolute mess right now. The error you're seeing is from a load balancer for TronGrid.
> 
> TRON has no standard for errors. There's probably about 5 different ways in which the API returns errors, and sometimes it also returns them despite a request being 200. I can look into "converting" the TronGrid HTML errors into JSON but it still leaves the error mess that the TRON HTTP API has.

thanks for the answer
