### ISSUE TITLE
Throw error when using address.toHex with invalid address.

### ISSUE THREAD

**Issue by metjm** [tronprotocol/tron-web#76]
Was just playing around with creating burn addresses, and `tronWeb.address.toHex('TronWatchMarketBuuuuuuuuuuuuuurn')`, which is an invalid address, returns `000000000000000000000000000000000000000000` as hex, which might(?) be accepted by some smart contracts as address. Should probably throw an error to prevent users from sending tokens to 0x0.

**Comment by serderovsh** [comment]
problem solved

**Comment by Kondax** [comment]
Fixed by #81
