### ISSUE TITLE
Proposal for new TronWeb API

### ISSUE THREAD

**Issue by Kondax** [tronprotocol/tron-web#8]
# TronWeb API Proposal
`TronWeb` was hastily developed without any prior planning on how to design the specifications. This has lead to an unorganised, slightly ambiguous API that will lead to potential developer confusion. It also means that migrating from `Web3` -> `TronWeb` will be a daunting task.

One of the many benefits of the `TVM` is that developers can ship nearly 1:1 smart contracts on both the `TVM` and `EVM`. Interacting with these contracts shouldn't be different.

`TronWeb` has been created to facilitate the need of interacting with the blockchain and smart contracts from the browser, desktop applications (Electron), mobile applications (*-native) and NodeJS. This proposal is for a new API spec that will resemble `Web3` (whilst still incorporating native TRON features) as much as possible. Whilst I have attempted to include all `Web3` functionality, some of it is unique to Ethereum. I have ported the spec for as many functions as possible.

TRON has two request protocols:
- gRPC
- HTTP

**For the time being we plan on only supporting the HTTP protocol.** _However in the future_ we would like developers to be able to pass `new TronWeb.providers.gRPCProvider()` if they want to run over gRPC instead.

All `TronWeb` methods will return a promise. They will all take a last, optional parameter as a callback using the [error-first-style](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/) callback. If a callback is passed the promise will not be returned.

Each method would essentially do the following (should be interpreted as pseudo code):
```js
const injectPromise = (func, ...args) => {
    return new Promise((resolve, reject) => {
        func(...args, (err, res) => {
            if(err)
                reject(err);
            else resolve(res);
        });
    });
},

const promiseInjector = scope => {
    return (func, ...args) => {
        return injectPromise(func.bind(scope), ...args);
    }
}

class TronWeb {
    injectPromise = utils.promiseInjector(this);

    getEventByTransacionID(transactionID, callback = false) {
        if(!callback)
            return this.injectPromise(this.getEventByTransacionID, transactionID);

        const event = getEventSomehow(transactionID);
        callback(null, event);
    }
}
```

This will maintain `Web3` compatibility whilst still offering the benefits of promises.

## HTTP Provider
This will send RPC over HTTP to nodes that support it. The provider will be accessible under `new TronWeb.providers.HttpProvider()` and take the following arguments:
- `host`: The host of the node, in the format `http://ip:port`
- `[timeout=30000]`: The global timeout for requests to the node in milliseconds. This should be able to be overridden on a per-use scenario.
- `[user=false]`: User for HTTP authentication
- `[password=false]`: Password for HTTP authentication, requires `user` to be set.
- `[headers={}]`: Additional headers to be attached to all requests. Individual requests will override these headers.
- `[statusPage='/']`: Page to query when calling `isConnected()`

The following methods will be exposed:
- `setStatusPage(statusPage = '/')`: Sets the status page to query.
- `async isConnected()`: Returns type `boolean`, this will make a call to the node (fetch latest block number) to verify that the mode connection is successful.
- `async request(url, payload = {}, method = 'get')`: Returns a promise. The promise will be resolved if the node sends a 2xx status, otherwise it will throw the error.

For more details see [`web3.providers.HttpProvider`](https://github.com/ethereum/web3.js/blob/develop/lib/web3/httpprovider.js).

## TronWeb API
`class TronWeb`:
- constructor(fullNode, solidityNode, eventServer = false, privateKey = false):
	- `fullNode`: A provider connected to a valid full node
	- `solidityNode`: A provider connected to a valid solidity node
	- `[eventServer]`: Optional for smart contract events. Expects a valid event server URL
        - `[privateKey]`: Optional default private key used when signing transactions
	
- isConnected():
	- Returns an object with the structure `{ fullNode: bool, solidityNode: bool, eventServer: bool }`

- setFullNode(provider):
	- `provider`: A provider connected to a valid full node

- setSolidityNode(provider):
	- `provider`: A provider connected to a valid solidity node

- setEventServer(eventServer):
	- `[eventServer=false]`: False to unset the event server, or a valid event server URL

- currentProviders():
	- Returns an object with the structure `{ fullNode: TronWeb.provider, solidityNode: TronWeb.provider, eventServer: string|bool }`

- currentProvider():
    -An alias of `currentProviders()`

- sha3(string, options):
	- `string`: The string to hash (using Keccak-256 SHA3 Algorithm)
	- `[options={}]`: Configure `encoding: hex` if the string to hash is encoded in hexadecimal format

- toHex(input):
	- `input`: Either a string, number, object, array or BigNumber. Objects / Arrays will be stringified with `JSON.stringify` first.

- toAscii(hex):
	- `hex`: Hexadecimal-encoded string to be converted to ASCII

- fromAscii(string):
	- `string`: An ASCII string to be converted to hexadecimal

- toDecimal(hex):
	- `hex`: Hexadecimal-encoded string to be converted to its number representation

- fromDecimal(number):
	- `number`: Number (or string) to be converted to hexadecimal

- fromSun(sun):
	- `sun`: Number in SUN (1 / 1,000,000 TRX) to be converted to TRX

- toSun(trx):
	- `trx`: Number in TRX to be converted to SUN (1 / 1,000,000 TRX)

- toBigNumber(amount):
	- `amount`: Amount that's a number, number string or hexadecimal string of a number to be converted to a BigNumber

- isAddress(address):
	- `address`: Either hex encoded or base58 encoded address

- address:
	- fromHex(address):
		- `address`: Hexadecimal encoded address
		- Returns the base58 representation of the supplied address

	- toHex(address):
		- `address`: Base58 encoded address
		- Returns the hexadecimal representation of the supplied address

- trx:
	- defaultAccount
		- The default account (hexadecimal address) to use when creating transactions

	- defaultBlock
		The default block to use when creating transactions. Can be one of the following:
		-	Number: a block number
		-	String "earliest": the genesis block
		-	String "latest": the latest block (at the time of creating the transaction)

	- getBalance(address [, callback]):
		- `[address=this.defaultAccount]`: The address to fetch the balance of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getBandwidth(address [, callback]):
		- `[address=this.defaultAccount]`: The address to fetch the bandwidth of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getBlock(blockIdentifier [, callback]):
		- `[blockIdentifier=this.defaultBlock]`: The block to fetch
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getBlockTransactionCount(blockIdentifier [, callback]):
		- `[blockIdentifier=this.defaultBlock]`: The block to list the transaction count of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTransaction(transactionHash [, callback]):
		- `transactionHash`: The transaction hash of the transaction to fetch
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTransactionFromBlock(blockIdentifier, index [, callback]):
		- `blockIdentifier`: The block to search
		- `index`: The index of the transaction in the fetched block
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTransactionCount(address [, callback]):
		- `address`: Hexadecimal address to fetch the transaction count of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTokenFromAddress(address [, callback]):
		- `address`: Address of the token issuer
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTokenFromID(assetID [, callback]):
		- `assetID`: The asset ID (the token name) of the token
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getContract(contractAddress [, callback]):
		- `contractAddress`: Hexadecimal address of the contract
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- listNodes([callback]):
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the list of connected nodes.	

	- listSuperRepresentatives([callback]):
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns a list of all accounts that have applied for SR.

	- listAssets():
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns a list of all issued tokens.

	- listAssetsPaginated(limit [, offset [, callback]]):
		- `limit`: Total amount of tokens to fetch
		- `offset`: Offset at which to start returning tokens
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- timeUntilNextVoteCycle([callback]):
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- sendTransaction(to, amount, privateKey, [, callback]):
		- `to`: Hexadecimal address of the receiving account
		- `amount`: Amount of TRX **in SUN** to send
		- `privateKey`: Hexadecimal private key of the account to send the TRX from
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the transaction result.

	- sendAsset(to, amount, assetID, privateKey, [, callback]):
		- `to`: Hexadecimal address of the receiving account
		- `amount`: Amount of the asset to send
		- `assetID`: The asset ID (name of the token) to send
		- `privateKey`: Hexadecimal private key of the account to send the asset from
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the transaction result.

	- sendRawTransaction(signedTransaction [, callback]):
		- `signedTransaction`: An already signed transaction to broadcast to the network
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the transaction result.

	- sign(transaction, privateKey [, callback]):
		- `transaction`: An unsigned hexadecimal transaction to sign
		- `privateKey`: Hexadecimal private key of the account to sign the transaction with
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the signed transaction.

	- contract(abiArray):
		- `abiArray`: An array of with descriptions of functions and events of the contract
		- Returns a new contract object which can be initiated as follows:
		```js
		const MyContract = tronWeb.trx.contract(abiArray);
		// Get contract from address
		const contractInstance = MyContract.at(address);
		// Deploy new contract
		const contractInstance = MyContract.new(params);
		const contractData = contractInstance.getData(); // hex representation of the contract
		```

- witness:
	- apply(privateKey, url [, callback]):
		- `privateKey`: Hexadecimal private key of the account applying for SR
		- `url`: Homepage url of the SR
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the result from the node. This costs 9,999 TRX.

	- submitVotes(votes [, callback]):
		-  `votes`: Object in the format `{ [srAddress]: voteCount }` for the SRs to vote for. `voteCount` is in SUN.
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the result from the node.

	- withdraw(privateKey [, callback]):
		- `privateKey`: Hexadecimal private key of the SR requesting the withdraw
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the result from the node.

-	transactionBuilder:
	-	createToken(tokenObject [, callback]):
		-	`tokenObject`: Token object to send to the node with the following structure:
			```js
			{
				name: name of the token,
				abbr: abbreviation of the token,
				url: homepage url of the token,
				description: description of the token,
				totalSupply: Integer value of the total token supply,
				frozenSupply: Amount of the token to be frozen when created (defaults 0),
				frozenDuration: Amount of days to freeze the frozenSupply for (minimum 3),
				startTime: Timestamp of the start of the token sale,
				endTime: Timestamp of the end of the token sale,
				trxAmount: Amount the token costs in SUN
			}
			```
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- sendTrx(to, amount, from [, callback]):
		- `to`: Hexadecimal address of the recipient
		- `amount`: Amount of TRX **in SUN** to send to the recipient
		- `from`: Hexadecimal address of the sender
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- sendAsset(to, amount, assetID, from [, callback]):
		- `to`: Hexadecimal address of the recipient
		- `amount`: Amount of the asset to send
		- `assetID`: The asset ID (the token name) to send to the recipient
		- `from`: Hexadecimal address of the sender
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- purchaseAsset(tokenIssuer, assetID, amount, buyer [, callback]):
		- `tokenIssuer`: Hexadecimal address of the owner of the token
		- `assetID`: The asset ID (the token name) to purchase
		- `amount`: The amount of the token to purchase
		- `buyer`: Hexadecimal address of the buyer
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- freezeBalance(address, amount, duration [, callback]):
		- `address`: Hexadecimal address of the account requesting the freeze
		- `amount`: Amount of TRX **in SUN** to freeze
		- `[duration=3]` Duration (in days) to freeze the TRX for. Minimum of 3.
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned. 
		- Returns the unsigned transaction.

	- unfreezeBalance(address [, callback]):
		- `address`: Hexadecimal address of the account requesting the unfreeze
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- vote(votes, address [, callback]):
		-  `votes`: Object in the format `{ [srAddress]: voteCount }` for the SRs to vote for. `voteCount` is in SUN.
		- `address`: Hexadecimal address of the voter.
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.
	
	- applyForSR(address, url [, callback]):
		- `address`: Hexadecimal address of the account applying for SR.
		- `url`: Homepage url of the SR
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction. This will cost 9,999 TRX.

	- withdrawBlockRewards(address [, callback]):
		- `address`: Hexadecimal address of the SR requesting the withdraw
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

  - createSmartContract(abi, bytecode, feeLimit, address, callValue, bandwidthLimit [, callback]):
    - `abi`: The contract's ABI
    - `bytecode`: The contract's bytecode in HEX
    - `feeLimit`: Maximum TRX consumption **in SUN**
    - `address`: Hexadecimal address of the account requesting to create the contract
    - `[callValue=0]`: Optional amount of TRX in SUN to pay into the contract
    - `[bandwidthLimit]0]`: Optional percentage of the issuer's bandwidth to share with contract users
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- triggerSmartContract(contractAddress, functionSelector, callValue, feeLimit, parameters, address [, callback]):
    - `contractAddress`: Hexadecimal address of the smart contract
    - `functionSelector`: Signature of the function to trigger
    - `callValue`: The amount of TRX **in SUN** to pay into the contract
    - `feeLimit`: Maximum TRX consumption **in SUN**
    - `[parameters=[]]`: Optional parameters to pass to the function
    - `address`: Hexadecimal address of the account requesting the trigger
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
    - Returns the unsigned transaction.
    
- getEventResult(contractAddress, eventName, blockNumber [, callback]):
    - `contractAddress`: Hexadecimal address of the smart contract
    - `[eventName=false]`: Optional name of the event to query
    - `[blockNumber=false]`: Optional block number to query events from
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
    - Returns any found events.
  
- getEventByTransactionID(transactionID [, callback]):
    - `transactionID`: The transaction ID to query for events
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
  
- createAccount([callback]):
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
    - Returns a keypair for a new account.
  
There are some contracts missing from the API spec. This does not mean they will not be included - this proposal
is merely for showing how the API could be structured. The API will still export all contract types.
  
## Example
```js
import TronWeb from 'TronWeb';

const fullNode = new TronWeb.providers.HttpProvider('http://127.0.0.1:8090');
const solidityNode = new TronWeb.providers.HttpProvider('http://127.0.0.1:8091');
const eventServer = 'http://127.0.0.1:18891'; // This will only ever run over HTTP, not gRPC

const tronWeb = new TronWeb(fullNode, solidityNode, eventServer);

tronWeb.createAccount(({ privateKey, address }) => {
  console.log(`New account generated with privateKey ${privateKey}, hexadecimal address ${address}`);
});
```

## Node Proxying
Nodes run over HTTP (not HTTPS) which can pose a security risk. Requests are vulnerable to MiTM
and can therefore risk the funds of the developer. For this reason, TronWatch have created the following proposal:

`https://proxy.tron.watch/nodeIP:nodePort/someNodeMethod`

TronWatch will provide a proxy endpoint that proxies all requests to the specified node. This can prevent _local MiTM_,
such as if a user were using public wifi. The connection between the TronWatch server and the node will not be secured,
therefore it is vulnerable to MiTM during that process and is unfortunately not a solution for all.

The proxy function will be published in a GitHub repository with deployment instructions should a developer wish to deploy
their own proxy.

**Comment by Kondax** [comment]
## Missing `Web3` Functionality
`web3.version`
`web3.net`
`web3.eth.call` (not currently possible, will be implemented when it is)
`web3.getUncle`
`web3.getBlockUncleCount`
`web3.getTransactionReceipt`
`web3.register`
`web3.unregister`
`web3.syncing`
`web3.coinbase`
`web3.gasPrice`
`web3.accounts`
`web3.mining`
`web3.getStorageAt`
`web3.getCode`
`web3.estimateGas`
`web3.filter`
`web3.getCompilers`
`web3.compile.Ill`
`web3.compile.serpent`
`web3.namereg`
`web3.sendIBANTransaction`
`web3.iban`
`web3.db`
`web3.shh`
`web3.reset`

If / when the above methods are available in TRON they will be added to the API spec.

`web3.version` will only be able to export the API version.

**Comment by Kondax** [comment]
TVM isn't enabled on the mainnet at the moment so it shouldn't be an issue
for now.

**Comment by sullof** [comment]
@Kondax We'd like to keep the maximum compatibility with Web3. Due to the differences between TVM and EVM, tho, there are a lot of methods which are Tron-only. It would be nice to have some kind of annotation to signal the EVM-compatible methods or, at the opposite, the TVM-only one. What do you think?

**Comment by Kondax** [comment]
@sullof I agree. If you track PR #9 you will see the progress of the new implementation. This has differed slightly from the above proposal.

The documentation will provide a list of which methods are interchangeable (to an extent).

`tronWeb.trx.getTransaction` is currently implemented. Yes, `trx` is used as an abbreviation for a transaction but it is also the official abbreviation for TRON. I would see the issue if it was `tx` but I don't think `trx` should cause that much of an issue.

**Comment by sullof** [comment]
Sorry, I closed by mistake.
Btw, I agree about `trx` above.

**Comment by Kondax** [comment]
@sullof Just to update you, my 2.0 implementation is now feature complete
